name: Publish Artifacts

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
  release:
    types: [published]

env:
  GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Bylaws Artifact
    container:
      image: pandoc/latex:2.19-ubuntu
    steps:
    - name: Checkout
      uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: Prebuild Dependancies 
      run: |
        apt-get update
        apt-get install make
        tlmgr install enumitem lastpage lineno
    - name: Build document formats
      run: make build    
    - name: Upload PDF Document
      uses: actions/upload-artifact@v3
      id: upload-pdf
      with:
        path: ./bylaws.pdf
    - name: Upload Word DOC
      uses: actions/upload-artifact@v3
      id: upload-worddoc
      with:
        path: ./bylaws.docx
    - name: Upload HTML
      uses: actions/upload-artifact@v3
      id: upload-html
      with:
        path: ./bylaws.html
    - if: github.event_name == 'release' && github.event.action == 'published'
      name: Get Release
      id: release
      uses: bruceadams/get-release@v1.2.0
    - if: github.event_name == 'release' && github.event.action ==  'published'
      name: Attach PDF Document to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ./bylaws.pdf
        asset_name: bylaws.pdf
    - if: github.event_name == 'release' && github.event.action ==  'published'
      name: Attach WordDoc to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ./bylaws.docx
        asset_name: bylaws.docx
    - if: github.event_name == 'release' && github.event.action ==  'published'
      name: Attach HTML to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ./bylaws.html
        asset_name: bylaws.html
